services:
  db:
    image: postgres:15-alpine
    container_name: helpdesk_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - helpdesk_network

  api:
    build: ./backend
    container_name: helpdesk_api
    restart: always
    environment:
      # Puxando as credenciais seguras do seu arquivo .env
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - helpdesk_network
    volumes:
      - ./backend:/app

networks:
  helpdesk_network:
    driver: bridge

volumes:
  pgdata:
